
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;

public class Progarm {
    public static void main(String[] args) {
        Department Deparment1 = new Department();
        Deparment1.id = 1;
        Deparment1.name = "bảo vệ";
        Department Deparment2 = new Department();
        Deparment2.id = 2;
        Deparment2.name = "nhân viên";
        Department Deparment3 = new Department();
        Deparment1.id = 3;
        Deparment1.name = "giám  đốc";
        Position Position1 = new Position() ;
        Position1.id=1;
        Position1.Name= Position.PositionName.DEV;
        Position position2 = new Position() ;
        position2.id=2;
        position2.Name= Position.PositionName.TEST;
        Position Position3 = new Position() ;
        Position3.id=3;
        Position3.Name= Position.PositionName.PM;
        Account account1= new Account();
        account1.id=1;
        account1.positionID =Position1;
        account1.departmentID =Deparment1;
        account1.username="huuvu";
        account1.createDate=LocalDate.now();
        Account account2= new Account();
        account2.id=2;
        account2.positionID =Position1;
        account2.departmentID =Deparment2;
        account2.username="nguyenvana";
        account2.createDate=LocalDate.now();
        Account account3= new Account();
        account3.id=3;
        account3.positionID =Position3;
        account3.departmentID =Deparment3;
        account3.username="nguyenvanb";
        account3.createDate=LocalDate.now();
        Group group1 =new Group();
        group1.id=1;
        group1.Name="group1";
        group1.CreateDate=LocalDate.now();
        group1.CreatorID=account1;
        Group group2 =new Group();
        group2.id=2;
        group2.Name="group2";
        group2.CreateDate=LocalDate.now();
        group2.CreatorID=account2;
        Group group3 =new Group();
        group3.id=3;
        group3.Name="group1";
        group3.CreateDate=LocalDate.now();
        group3.CreatorID=account3;
        account2.group=new Group[] {group1,group2,group3};
        account1.group=new Group[] {group1,group2};
        account3.group=new Group[]  {group1,group3};
        group1.accounts= new Account[]{account1,account2};
        group2.accounts =new  Account[]{account1,account3,account2};
        group3.accounts=new Account[]{account2,account3};
        GroupAccount GroupAccount1 =new GroupAccount();
        GroupAccount1.id=1;
        GroupAccount1.AccountID=account1;
        GroupAccount1.JoinDate=LocalDate.now();
        GroupAccount GroupAccount2 =new GroupAccount();
        GroupAccount2.id=2;
        GroupAccount2.AccountID=account2;
        GroupAccount2.JoinDate=LocalDate.now();
        GroupAccount GroupAccount3 =new GroupAccount();
        GroupAccount3.id=3;
        GroupAccount3.AccountID=account3;
        GroupAccount3.JoinDate=LocalDate.now();
        TypeQuestion typeQuestion1 =new TypeQuestion();
        typeQuestion1.id=1;
        typeQuestion1.Name=TypeQuestion.TypeQuestionName.Esaasy;
        TypeQuestion typeQuestion2 =new TypeQuestion();
        typeQuestion2.id=2;
        typeQuestion2.Name=TypeQuestion.TypeQuestionName.Esaasy;
        TypeQuestion typeQuestion3 =new TypeQuestion();
        typeQuestion3.id=3;
        typeQuestion3.Name=TypeQuestion.TypeQuestionName.Esaasy;
        CategoryQuestion categoryQuestion1 =new CategoryQuestion();
        categoryQuestion1.id=1;
        categoryQuestion1.Name="java";
        CategoryQuestion categoryQuestion2 =new CategoryQuestion();
        categoryQuestion2.id=2;
        categoryQuestion2.Name="php";
        CategoryQuestion categoryquestion3 =new CategoryQuestion();
        categoryquestion3.id=3;
        categoryquestion3.Name="c++";
        Question question1 =new Question();

        question1.id=1;
        question1.CategoryID=categoryQuestion1;
        question1.Content="java là gì";
        question1.TypedID=typeQuestion1;
        question1.CreateDate= LocalDate.now();
        question1.CreatorID=account1;
        Question question2 =new Question();
        question2.id=2;
        question2.CategoryID=categoryQuestion2;
        question2.Content="java là gì";
        question2.TypedID=typeQuestion2;
        question2.CreateDate= LocalDate.now();
        question2.CreatorID=account2;
        Question question3 =new Question();
        question3.id=3;
        question3.CategoryID=categoryQuestion1;
        question3.Content="java là gì";
        question3.TypedID=typeQuestion1;
        question3.CreateDate= LocalDate.now();
        question3.CreatorID=account3;
        Answer answer1= new Answer();
        answer1.id=1;
        answer1.Content="java là ngôn ngữ lập ";
        answer1.QuestionID=question1;
        answer1.isCorrect=true;
        Answer answer2= new Answer();
        answer2.id=2;
        answer2.Content="php phần mền ";
        answer2.QuestionID=question2;
        answer2.isCorrect=false;
        Answer answer3= new Answer();
        answer3.id=3;
        answer3.Content="c++ là ngôn ngữ lập ";
        answer3.QuestionID=question3;
        answer3.isCorrect=true;
        Exam exam1 =new Exam();
        exam1.id =1;
        exam1.Code="001A";
        exam1.Title="tieu đề ";
        exam1.CategoryID=categoryQuestion1;
        exam1.CreateDate=LocalDateTime.now();
        exam1.CreatorID=account1;
        exam1.Duration =90;
        Exam exam2 =new Exam();
        exam2.id =2;
        exam2.Code="001A";
        exam2.Title="tieu đề 2";
        exam2.CategoryID=categoryQuestion1;
        exam2.CreateDate=LocalDateTime.now();
        exam2.CreatorID=account2;
        exam2.Duration =90;
        Exam exam3 =new Exam();
        exam3.id =3;
        exam3.Code="001A";
        exam3.Title="tieu đề 1";
        exam3.CategoryID=categoryQuestion2;
        exam3.CreateDate=LocalDateTime.now();
        exam3.CreatorID=account3;
        exam3.Duration =90;
        ExamQuestion examQuestion1 =new ExamQuestion();
        examQuestion1.Examid=exam1;
        examQuestion1.QuestionId=question1;
        ExamQuestion examQuestion2 =new ExamQuestion();
        examQuestion2.Examid=exam2;
        examQuestion2.QuestionId=question2;
        ExamQuestion examQuestion3 =new ExamQuestion();
        examQuestion3.Examid=exam3;
        examQuestion3.QuestionId=question1;
        System.out.println("họ và tên: " + account1.username );
        System.out.println("ngày tạo: " +account1.createDate);
        System.out.println( "phòng ban: "+ Deparment1.name);
        System.out.printf("chức vụ:"+Position1.Name);
        System.out.println("tên group" + group1.Name);
        System.out.println("người tạo group"+ account1.username);
        System.out.println("ngày tạo group"+group1.CreateDate);
        System.out.println("ngày tham gia group"+ GroupAccount1.JoinDate);
        System.out.println("Noi dung câu hỏi"+question1.Content);
        System.out.println("dịnh danh câu hỏi"+categoryQuestion1.Name );
        System.out.println("ten câu hỏi"+typeQuestion1.Name);
        System.out.println("nguoi tao ra cau hoi"+account1.username);
        System.out.println("ngay tao ra cau hoi"+question1.CreateDate);
        System.out.println("noi dung cau tra loi"+answer1.Content);
        System.out.println("dinh danh cau hoi"+ answer1.QuestionID);
        System.out.println(" câu trả lời này đúng hay sai "+answer1.isCorrect);
        System.out.println("code đề thi" + exam1.Code);
        System.out.println("tieu đề"+exam1.Title);
        System.out.println("dinh danh đề thi"+exam1.CategoryID);
        System.out.println("thoi gian thi"+exam1.Duration);
        System.out.println("nguoi tao de thi"+exam1.CreatorID);
        System.out.println("ngày tạo đề th"+exam1.CreateDate);
        System.out.println("định danh đề thi "+examQuestion1.Examid);
        System.out.println("định dnah câu hỏi"+examQuestion1.QuestionId);


    }
}
